export const FEATURES = [
  {
    id: 0,
    title: 'Predictive Analytics',
    description: 'Surface trends before they happen',
    detail: 'Our ML pipeline processes 10M+ events/sec and surfaces anomalies with sub-100ms latency. Connect any data source in minutes.',
    icon: 'ArrowTrendingUp',
    accentColor: 'var(--forsythia)',
    metric: '10M+',
    metricLabel: 'events/sec',
  },
  {
    id: 1,
    title: 'Visual Intelligence',
    description: 'Turn raw data into live insights',
    detail: 'Interactive dashboards that auto-update as your data changes. Export to any format, share with one link.',
    icon: 'ChartPie',
    accentColor: 'var(--deep-saffron)',
    metric: '99.9%',
    metricLabel: 'uptime SLA',
  },
  {
    id: 2,
    title: 'Workflow Automation',
    description: 'Eliminate repetitive operations',
    detail: 'Drag-and-drop pipeline builder with 200+ native connectors. Run on schedule, on event, or on demand.',
    icon: 'Cog8Tooth',
    accentColor: 'var(--mystic-mint)',
    metric: '200+',
    metricLabel: 'connectors',
  },
  {
    id: 3,
    title: 'Self-Healing Pipelines',
    description: 'Resilience built into every layer',
    detail: 'Automatic retry, dead-letter queues, and circuit breakers so your data never stops flowing — even when upstream systems fail.',
    icon: 'ArrowPath',
    accentColor: 'var(--forsythia)',
    metric: '<100ms',
    metricLabel: 'recovery time',
  },
  {
    id: 4,
    title: 'Unified Data Layer',
    description: 'One schema, every source',
    detail: 'Normalize data from databases, APIs, files, and streams into a single consistent schema automatically.',
    icon: 'Cube',
    accentColor: 'var(--deep-saffron)',
    metric: '500+',
    metricLabel: 'schema types',
  },
  {
    id: 5,
    title: 'API-First Architecture',
    description: 'Build on top of DataFlow',
    detail: 'Every feature is accessible via REST and GraphQL. SDKs for TypeScript, Python, Go, and Rust.',
    icon: 'Link',
    accentColor: 'var(--mystic-mint)',
    metric: '4',
    metricLabel: 'official SDKs',
  },
]
